In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("http://bilkav.com/veriler.csv")
df

ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k

In [3]:
df[['boy','kilo','yas']]

boy  kilo  yas
0   130    30   10
1   125    36   11
2   135    34   10
3   133    30    9
4   129    38   12
5   180    90   30
6   190    80   25
7   175    90   35
8   177    60   22
9   185   105   33
10  165    55   27
11  155    50   44
12  160    58   39
13  162    59   41
14  167    62   55
15  174    70   47
16  193    90   23
17  187    80   27
18  183    88   28
19  159    40   29
20  164    66   32
21  166    56   42

In [4]:
class Animal:
    name = ""
    def eat(self):
        print("I can eat")

class Dog(Animal):
    def display(self):
        print("My name is ", self.name)

labrador = Dog()
labrador.name = "Rohu"
labrador.eat()
labrador.display()

I can eat
My name is  Rohu


In [18]:
# Eksik verileri tamamlama
df = pd.read_csv("http://bilkav.com/eksikveriler.csv")

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")

Yas = df.iloc[:,3:4].values
imputer = imputer.fit_transform(Yas)
df.iloc[:,3:4] = imputer
df

ulke  boy  kilo    yas cinsiyet
0    tr  130    30  10.00        e
1    tr  125    36  11.00        e
2    tr  135    34  10.00        k
3    tr  133    30   9.00        k
4    tr  129    38  12.00        e
5    tr  180    90  30.00        e
6    tr  190    80  25.00        e
7    tr  175    90  35.00        e
8    tr  177    60  22.00        k
9    us  185   105  33.00        e
10   us  165    55  27.00        k
11   us  155    50  44.00        k
12   us  160    58  28.45        k
13   us  162    59  41.00        k
14   us  167    62  55.00        k
15   fr  174    70  47.00        e
16   fr  193    90  28.45        e
17   fr  187    80  27.00        e
18   fr  183    88  28.00        e
19   fr  159    40  29.00        k
20   fr  164    66  32.00        k
21   fr  166    56  42.00        k

In [6]:

# Sözel verileri sayısal veriye çevirme

# Label Encoding
cinsiyet = df.iloc[:,4:5].values

from sklearn import preprocessing
le = preprocessing.LabelEncoder()
cinsiyet = le.fit_transform(cinsiyet)
df.iloc[:,4:5] = cinsiyet
df

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


ulke  boy  kilo    yas  cinsiyet
0    tr  130    30  10.00         0
1    tr  125    36  11.00         0
2    tr  135    34  10.00         1
3    tr  133    30   9.00         1
4    tr  129    38  12.00         0
5    tr  180    90  30.00         0
6    tr  190    80  25.00         0
7    tr  175    90  35.00         0
8    tr  177    60  22.00         1
9    us  185   105  33.00         0
10   us  165    55  27.00         1
11   us  155    50  44.00         1
12   us  160    58  28.45         1
13   us  162    59  41.00         1
14   us  167    62  55.00         1
15   fr  174    70  47.00         0
16   fr  193    90  28.45         0
17   fr  187    80  27.00         0
18   fr  183    88  28.00         0
19   fr  159    40  29.00         1
20   fr  164    66  32.00         1
21   fr  166    56  42.00         1

In [7]:
# Metinsel veriyi sayısal veriye çevirme

# One Hot Encoder
ulke = df.iloc[:,0:1].values

from sklearn import preprocessing
ohe = preprocessing.OneHotEncoder()

ulke = ohe.fit_transform(ulke).toarray()
ulke

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [8]:
sonuc = pd.DataFrame(data=ulke, index = range(len(ulke)), columns=["fr", "tr", "usa"])
sonuc

fr   tr  usa
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0

In [9]:
sonuc_1 = df.iloc[:,1:]
sonuc_1

boy  kilo    yas  cinsiyet
0   130    30  10.00         0
1   125    36  11.00         0
2   135    34  10.00         1
3   133    30   9.00         1
4   129    38  12.00         0
5   180    90  30.00         0
6   190    80  25.00         0
7   175    90  35.00         0
8   177    60  22.00         1
9   185   105  33.00         0
10  165    55  27.00         1
11  155    50  44.00         1
12  160    58  28.45         1
13  162    59  41.00         1
14  167    62  55.00         1
15  174    70  47.00         0
16  193    90  28.45         0
17  187    80  27.00         0
18  183    88  28.00         0
19  159    40  29.00         1
20  164    66  32.00         1
21  166    56  42.00         1

In [10]:
result_1 = pd.concat([sonuc,sonuc_1], axis=1)
result_1

fr   tr  usa  boy  kilo    yas  cinsiyet
0   0.0  1.0  0.0  130    30  10.00         0
1   0.0  1.0  0.0  125    36  11.00         0
2   0.0  1.0  0.0  135    34  10.00         1
3   0.0  1.0  0.0  133    30   9.00         1
4   0.0  1.0  0.0  129    38  12.00         0
5   0.0  1.0  0.0  180    90  30.00         0
6   0.0  1.0  0.0  190    80  25.00         0
7   0.0  1.0  0.0  175    90  35.00         0
8   0.0  1.0  0.0  177    60  22.00         1
9   0.0  0.0  1.0  185   105  33.00         0
10  0.0  0.0  1.0  165    55  27.00         1
11  0.0  0.0  1.0  155    50  44.00         1
12  0.0  0.0  1.0  160    58  28.45         1
13  0.0  0.0  1.0  162    59  41.00         1
14  0.0  0.0  1.0  167    62  55.00         1
15  1.0  0.0  0.0  174    70  47.00         0
16  1.0  0.0  0.0  193    90  28.45         0
17  1.0  0.0  0.0  187    80  27.00         0
18  1.0  0.0  0.0  183    88  28.00         0
19  1.0  0.0  0.0  159    40  29.00         1
20  1.0  0.0  0.0  164    66  32.00         1
21  1.0  0.0  0.0  166    56  42.00         1

In [11]:
data = result_1.to_csv('veriler.csv', index=False)

In [12]:
df = pd.read_csv("veriler.csv")
df

fr   tr  usa  boy  kilo    yas  cinsiyet
0   0.0  1.0  0.0  130    30  10.00         0
1   0.0  1.0  0.0  125    36  11.00         0
2   0.0  1.0  0.0  135    34  10.00         1
3   0.0  1.0  0.0  133    30   9.00         1
4   0.0  1.0  0.0  129    38  12.00         0
5   0.0  1.0  0.0  180    90  30.00         0
6   0.0  1.0  0.0  190    80  25.00         0
7   0.0  1.0  0.0  175    90  35.00         0
8   0.0  1.0  0.0  177    60  22.00         1
9   0.0  0.0  1.0  185   105  33.00         0
10  0.0  0.0  1.0  165    55  27.00         1
11  0.0  0.0  1.0  155    50  44.00         1
12  0.0  0.0  1.0  160    58  28.45         1
13  0.0  0.0  1.0  162    59  41.00         1
14  0.0  0.0  1.0  167    62  55.00         1
15  1.0  0.0  0.0  174    70  47.00         0
16  1.0  0.0  0.0  193    90  28.45         0
17  1.0  0.0  0.0  187    80  27.00         0
18  1.0  0.0  0.0  183    88  28.00         0
19  1.0  0.0  0.0  159    40  29.00         1
20  1.0  0.0  0.0  164    66  32.00         1
21  1.0  0.0  0.0  166    56  42.00         1

In [13]:
bagimsiz_degiskenler = df.iloc[:,:-1]
bagimli_degiskenler = df.iloc[:,-1]

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(bagimsiz_degiskenler, bagimli_degiskenler, test_size=0.33, random_state=0)

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [15]:
X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)

In [16]:
print(X_train)
print("*"*75)
print(X_test)

[[-0.63245553  0.8660254  -0.40824829  0.45049444 -0.29657884 -0.24717129]
 [-0.63245553  0.8660254  -0.40824829  1.00824945  0.5096549   0.03416189]
 [ 1.58113883 -1.15470054 -0.40824829  1.13696215  0.91277178  0.35769504]
 [-0.63245553  0.8660254  -0.40824829 -1.6089087  -1.18343596 -1.18494855]
 [-0.63245553  0.8660254  -0.40824829 -1.35148331 -1.34468271 -1.372504  ]
 [-0.63245553  0.8660254  -0.40824829  0.57920713  0.91277178  0.50305051]
 [ 1.58113883 -1.15470054 -0.40824829  0.87953676  0.5096549   0.22171734]
 [-0.63245553 -1.15470054  2.44948974  0.79372829  1.51744708  0.78438369]
 [-0.63245553  0.8660254  -0.40824829  0.36468597  0.91277178  0.97193914]
 [ 1.58113883 -1.15470054 -0.40824829  0.70791983  0.8321484   0.31549506]
 [-0.63245553  0.8660254  -0.40824829 -1.43729177 -1.50592946 -1.46628173]
 [-0.63245553  0.8660254  -0.40824829 -1.56600447 -1.50592946 -1.372504  ]
 [ 1.58113883 -1.15470054 -0.40824829  0.32178174  0.10653803  2.09727185]
 [-0.63245553 -1.15470054